-- Copyright (c) 2026 Eric Grynspan. All rights reserved.
-- Run once in Snowflake console (as ACCOUNTADMIN or SYSADMIN)
-- Creates all objects needed for the healthcare_claims dbt project

USE ROLE ACCOUNTADMIN;

-- Warehouse (XS, auto-suspend after 60s to minimize cost)
CREATE WAREHOUSE IF NOT EXISTS HEALTHCARE_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND   = 60
    AUTO_RESUME    = TRUE
    COMMENT        = 'Healthcare Claims Pipeline — dev/demo';

-- Database + schemas
CREATE DATABASE IF NOT EXISTS HEALTHCARE_CLAIMS;
USE DATABASE HEALTHCARE_CLAIMS;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MART;

-- Role for dbt transformer
CREATE ROLE IF NOT EXISTS TRANSFORMER;

GRANT USAGE  ON WAREHOUSE HEALTHCARE_WH  TO ROLE TRANSFORMER;
GRANT USAGE  ON DATABASE  HEALTHCARE_CLAIMS TO ROLE TRANSFORMER;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE HEALTHCARE_CLAIMS TO ROLE TRANSFORMER;

-- RAW: read + write (loader writes here; dbt reads here)
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON ALL TABLES IN SCHEMA HEALTHCARE_CLAIMS.RAW TO ROLE TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA HEALTHCARE_CLAIMS.RAW TO ROLE TRANSFORMER;

-- STAGING + MART: full DDL (dbt creates/replaces views and tables)
GRANT ALL PRIVILEGES ON SCHEMA HEALTHCARE_CLAIMS.STAGING TO ROLE TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA HEALTHCARE_CLAIMS.MART    TO ROLE TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA HEALTHCARE_CLAIMS.STAGING TO ROLE TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA HEALTHCARE_CLAIMS.MART    TO ROLE TRANSFORMER;
GRANT CREATE VIEW  ON SCHEMA HEALTHCARE_CLAIMS.STAGING TO ROLE TRANSFORMER;

-- Assign transformer role to your user (replace YOUR_USERNAME)
GRANT ROLE TRANSFORMER TO USER YOUR_USERNAME;
